name: volna
description: "Волна — приложение психологической поддержки для родителей детей с особенностями"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.6.2
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1
  flutter_sound: ^9.27.0
  permission_handler: ^11.3.1
  http: ^1.2.2
  path_provider: ^2.1.5
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
